### ISSUE TITLE
Show warning when user types more than 40 words

### ISSUE THREAD

**Issue by MJafarMashhadi** [MJafarMashhadi/CodeDescriptionInformationCollector#1]

**Comment by shrBadihi** [comment]
الان هیچ خطایی رو نشون نمیده مبنی بر 40 کلمه بودن

**Comment by MJafarMashhadi** [comment]
در [این کامیت](https://github.com/MJafarMashhadi/CodeDescriptionInformationCollector/commit/bca6b8aa9bb10fa591b642d9b9346f747a527b71#diff-ba83003a4ba40cd09ff6a69d946d4948R76) درست شده روی سایت هم هست اما متن خطا خالی هست که فرمودید خودتون میگید که چی باشه

**Comment by shrBadihi** [comment]
الان شما برین خودتون امتحان کنید. 40 کلمه که وارد میشه بهش اجازه ی submit
داده میشه و submit میکنه. هیچ پیغام خالی فرستاده نمیشه.

**Comment by shrBadihi** [comment]
یه مسئله ی خیلی مهم دیگه. وقتی Try another زده میشه هم به عنوان comment ثبت
میشه. الان من دیشب 4 بار زدم اونو 4 comment خالی به نام من ثبت شده.

فردا صبح یا بعد از ظهر بیاین آزمایشگاه باید باهم بررسی کنیم.

2016-02-19 10:39 GMT+03:30 Sahar Badihi shr.badihi@gmail.com:

> الان شما برین خودتون امتحان کنید. 40 کلمه که وارد میشه بهش اجازه ی submit
> داده میشه و submit میکنه. هیچ پیغام خالی فرستاده نمیشه.
> 
> On Thu, Feb 18, 2016 at 8:46 PM, MohammadJafar MashhadiEbrahim <

**Comment by MJafarMashhadi** [comment]
Skip کامنت خالی محسوب میشه. توی اکسپورت نمیاد. توی شمارش‌ها هم محسوب نمیشه. نمیدونم مشکل چیه الان؟

**Comment by MJafarMashhadi** [comment]
یعنی اگر یک خلاصه‌ای شد ۴۱ کلمه اصلا اجازه‌ی سابمیت نداشته باشه؟ غیرمنطقیه!

**Comment by shrBadihi** [comment]
نه! بهش هیچ پیغامی نشون داده نمیشه

2016-02-19 11:34 GMT+03:30 MohammadJafar MashhadiEbrahim <
notifications@github.com>:

**Comment by MJafarMashhadi** [comment]
پیامی نیست چون هنوز متنش  رو نگفتید. متن approximate word count زرد میشه اگر دقت کنید

**Comment by shrBadihi** [comment]
پیام این باشه:
This seems to be a long summary.
