### ISSUE TITLE
Levels for users

### ISSUE THREAD

**Issue by MJafarMashhadi** [MJafarMashhadi/CodeDescriptionInformationCollector#16]
Starting to see the light
Taking your first steps
???? player (I couldn't read this one)
Middle of the way
Code squasher
Point warm
Proficient code summarized
Monster slayer

**Comment by MJafarMashhadi** [comment]
What is the interval for each one? e.g 0-40 : Starting to see the light, 40-100: Taking your first steps, etc

**Comment by shrBadihi** [comment]
intervals:
level 1 : 0-20
level 2: 20-60
level 3 : 60-100
level 4: 100-150
level 5: 150-200
level 6: 200-260
level 7: 260-320
level 8: 320- 400

**Comment by shrBadihi** [comment]
level 3 : good job! keep on.
