### ISSUE TITLE
finishing questions 

### ISSUE THREAD

**Issue by shrBadihi** [MJafarMashhadi/CodeDescriptionInformationCollector#43]
این 
feature
هم اون روز صحبت کردم
که نهایتا یه پرسشنامه با چندتا سوال خیلی ساده
مثل صفحه ی 
registration 
نشون داده بشه که پر کنن.
که میشه این رو تا 3 4 روز آینده انجام داد.

**Comment by MJafarMashhadi** [comment]
تو گوگل فرم درست کنید لینکش رو تو صفحه‌ی مرحله آخر میزارم
