### ISSUE TITLE
getting score twice from one method

### ISSUE THREAD

**Issue by shrBadihi** [MJafarMashhadi/CodeDescriptionInformationCollector#55]
![image](https://cloud.githubusercontent.com/assets/17319475/14667880/ae7f831e-06f6-11e6-9f77-d51c759ed86a.png)

**Comment by shrBadihi** [comment]
مورد دومی که گفتن یعنی امنیت سایت مسئله ی مهمیه

**Comment by shrBadihi** [comment]
من الان امتحان کردم که میشه 
back
 رو زد و دوبار امتیاز برای سابمیت یک خلاصه رو دریافت کرد.

**Comment by MJafarMashhadi** [comment]
البته مسأله‌ی «امنیتی» محسوب نمیشه

**Comment by MJafarMashhadi** [comment]
The same as #54 - closed as duplicate
